# Generated by Django 5.1.3 on 2025-01-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TemplateProcess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='upload_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
